version: "3.8"
services:
  telecom-db-postger:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./telecom.sql:/docker-entrypoint-initdb.d/telecom.sql
    networks:
      - week0
networks:
  week0: